### ISSUE TITLE
welcome message broke

### ISSUE THREAD

**Issue by pybites** [PyBites-Open-Source/karmabot#23]
```
Nov 01 13:40:06 pbkarmabot app/worker.1: Traceback (most recent call last): 
Nov 01 13:40:06 pbkarmabot app/worker.1:   File "main.py", line 32, in <module> 
Nov 01 13:40:06 pbkarmabot app/worker.1:     main() 
Nov 01 13:40:06 pbkarmabot app/worker.1:   File "main.py", line 18, in main 
Nov 01 13:40:06 pbkarmabot app/worker.1:     message = parse_next_msg() 
Nov 01 13:40:06 pbkarmabot app/worker.1:   File "/app/bot/slack.py", line 237, in parse_next_msg 
Nov 01 13:40:06 pbkarmabot app/worker.1:     welcome_msg = AUTOMATED_COMMANDS["welcome"](user_id)  # new user joining 
Nov 01 13:40:06 pbkarmabot app/worker.1:   File "/app/commands/welcome.py", line 48, in welcome_user 
Nov 01 13:40:06 pbkarmabot app/worker.1:     slack_id = bot.slack.format_user_id(user_id) 
Nov 01 13:40:06 pbkarmabot app/worker.1:   File "/app/bot/slack.py", line 84, in format_user_id 
Nov 01 13:40:06 pbkarmabot app/worker.1:     if SLACK_ID_FORMAT.match(user_id): 
Nov 01 13:40:06 pbkarmabot app/worker.1: TypeError: expected string or bytes-like object 
```

**Comment by pybites** [comment]
resolved, thanks @pogross
